name: Deploy AWS

on:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - "website/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # Get EC2 IP
      - name: Get IP
        id: ip
        working-directory: terraform
        run: echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      # Prepare HTML with version
      - name: Inject version
        run: |
          sed -i "s/__VERSION__/${GITHUB_SHA}/g" website/index.html

      # Deploy via SCP
      - name: Copy files to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

          scp -o StrictHostKeyChecking=no -i key.pem website/index.html ec2-user@${IP}:/tmp/

      # Move file to nginx folder
      - name: Move to nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${IP} "
            sudo mv /tmp/index.html /usr/share/nginx/html/index.html &&
            sudo systemctl reload nginx
          "
